add BGM #25
recursion-blue-team/tetris pull request #26
Opened 2023-01-25 23:37 UTC by yu-yaba

少し音量が大きいかもしれないです。

2023-01-26 08:09 UTC, K4-R4 requested changes
音声ファイル（フォルダ）がプッシュされていないようです
確認お願いします！

2023-01-26 14:38 UTC, yu-yaba commented
ほんとですね！ありがとうございます。
修正しました。

2023-01-26 22:21 UTC, K4-R4 approved these changes
最終的に音声が再生されることは確認しました。問題ないと思います

自分はブラウザの設定で自動再生ができませんでしたが設定いじって再生できるようになりました。自動再生は難しいようですね。

2023-01-27 01:04 UTC, yu-yaba commented
そのようですね。
webポリシー的に様々な手法が既に禁止されているようです。

2023-01-27 01:57 UTC, eddie-eights approved these changes
確認しました、ありがとうございます。
自動再生のタイミングは検討しましょう～
(ブラウザレンダリング時かスタートボタン押したときか)

2023-01-27 02:45 UTC, merged